package com.company;
@FunctionalInterface
interface myFunctionalInterface {
    void method1();
    //void methodd2();
}

class KeyPadPhone{

    void sendMessage(){
        System.out.println("Text message sent!");
    }
}

class AndroidPhone extends KeyPadPhone{
    @Override //------> First Annotations in java used to define override method
    void sendMessage(){
        System.out.println("Message sent via WhatsApp!");
    }
}


public class Annotations {
    @Deprecated //----> Second Annotation in java used to define deprecate methods
    public  static void   add()
    {
        int a=8;
        int b=9;
        int c= a+b;
        System.out.println(c);
    }
    public static void main(String args[]){
        //@SuppressWarnings("deprication"); //--> This annotation helps us to supress some warnings that are being generated by compiler.
        AndroidPhone Samsung = new AndroidPhone();
        Samsung.sendMessage();

        add();
    }
}




